version: '2'

networks:
    proxy:
    external: true
    internal:
    external: false

    services:
        carpentierpro:
            image: martincarp/carpentierprov2:latest
            labels:
                - traefik.backend=carpentier.pro
                - traefik.frontend.rule=Host:carpentier.pro
                - traefik.docker.network=proxy
                - traefik.enable=true
            ports:
                - 8080:8080
            networks:
                - internal
                - proxy
            restart: always