version: '3'

networks:
    proxy:
        external: true
    internal:
        external: false

services:
    carpentierpro:
        image: martincarp/carpentierprov2:latest
        ports:
          - "5230:80"
        labels:
          - traefik.backend=carpentierpro
          - traefik.frontend.rule=Host:test.carpentier.pro
          - traefik.docker.network=proxy
          - traefik.enable=true
        networks:
          - internal
          - proxy
        restart: always