version: '3'

networks:
    proxy:
        external: true
    internal:
        external: false

services:
    batlplatform:
        image: martincarp/carpentierprov2:latest
        labels:
            - traefik.backend=carpentierpro
            - traefik.frontend.rule=Host:carpentier.pro
            - traefik.docker.network=proxy
            - traefik.enable=true
        networks:
            - internal
            - proxy
        restart: always